package com.frankcooper.bank._1501_2000;

public class _5537 {

    static _5537 handler = new _5537();

    public static void main(String[] args) {

        String s = "ulastalu";
//        handler.validate(s);

        String a = "ulacfd", b = "jizalu";

        a = "ebaiodumrpnnqqezolehlrhyemeyfnjmemzngfwtzirwtjglstddxdetgfeabdoanatdmqtslurtyvzfrbtdpxxfytqflsjrgpkispknotmxcwwflclfhuoxxedgvytvgioyrhiubseadknghoprvigiukuvewokdsgbovwmebhnufogukizqjthtrvtmjcfkhsepctgiftxggpvpwjzlnuicbklcnxqpswuzgslofzsnlmivopjpwljdualdikubvyaodbrgrnezimzbwkriqukktgjnfbrelwfmiqvegwfwhljkoxxqaeqwwmbbynwdolcebjiqhddmbofneasbgpumjlakggzetweuumazwqkvwbvwdlqtvkzybfmtqeleewpkbxegfqkfywlcgrcghgzjfpqklxberdjiwmreuyxhopsqqowwltqswffyxiehnfxzoebfnmvzzmtezzmcxhuaetbawyaccvtpmhlacgcefdbfqfbdwbogggtmwcuvsbaohukfzranvwhkoyztuvecyluaiptuhxvcejqdajrnblsihrgdhwstakmswlceiioruehyrcohbonhnztwcdehwnpicogxrjbnuilsiolackrlbfukszkprgrnqzjdgcsmquriurkblneahrtrugkclfdtbyzgazcsuhlkjetesqarxvtaiwwvtnbqnlaeiuvdnujhvvzbbzwsdkfxkowssgbzwhnlbmbfptjmssfplzhdxjcrmunpuzqsyiqynwmqabjjjxklxdjpjoxiizracovkggaynygtzknvgdmexzdnyzzetolralqbjnlwfuzrssdlkjouqsurycrrojpmnbjvmbfjwejfvqvoxlzaumcujghmfyaiqmxqotoqyzwmpngbezhogpvbrntfmlymqrzzjrugmmwckfecnfhgdiasrogwqkvggfyclwspxljmhjenccqaxkxtmhouthihyyiaxuigvtseozlyrsfukfeezufzhbrupnqwkzyfcddelwebcdkeikjhhmltjqqsuaounqscgrvpbvvqvgcslhknpxmaaamgxhuxlpuycjpupxblzusahquuincahexwmpusrnjpsgwoirzzhdepqodowamsactyvcpbycxgoalfkxfandyyxwinaqlgdcrhxzrkuhjqvuovumctlfuobxhoekqpymxaxujleqlvftxmcidhmxlxskeujoswkhcftrnvryrlfvuavxtdssxkyjrrvqtlmaxkqbzmayssbosjmvefvbqgsnjwegmlzjvsjgirmessjpmrvqaqdahckjuzbrilsbmzbyggugyfwqinssnkepewruojdkxexwtcvknqvvqblfsqyzbmenbxngjkymsidoltagyqafaxatjgnmhyoiwpggmzydtmqhmjwizjsywwktsapxlgjpljgthvoohviqybcmirihjjweiswztmcxseqfcgnkrysovleeyaikyxwuklnjgwnjsfgjwhwzrynruvueochfgcyjkggbcwugmrpvlxoeuaisdqlxwfsckumhiozhhhkzjtljchjvbdbbhvzgopcrdursgpktgseszzprrnjcpolxrfzrtohhmcrhzulazrihrcarrljmvkydikjlmsepttovhvafwabdtjdfgwpmzqdxxrkyfuznszwxndpfctqgwcnfuzipgcsdrhcglkhnijaskbnipsfyeslesmekkwbrtajobzoutmkmbwaysidnnlcnhgmmnvoabqkfgjyvxrxanrkoqkrrotefielgssafngafmwqnvetrcrlxfbusakpkrpwysmbeykfldiaypmmhlfobdtjwpdowrngmpotktmxrpdgaxbgcxqscbbxvijlnmaahmvqziuvuwrdpfhxprdebjviqskkvlsxerveqpmvnfgetmgrerihrvmrdgbpauqwsipchvmjcoafwllhenngmydaptqrlmkqxnjtgfvjwiqhrnwhjplbfrxapdlhtjonutttfbhtkrogihkpxcuiltyxumfmjivnkfbiqoxoudrglxbpmmsfpixxgittcbjiwmzxbzwrxfgistcfisfcsomigeombqpcehzjvvslbtxzucqdfiecpnrzsxhqyeadgfsivezpkzdlhnyvstfrcfwwqtmjnumefmyshaseyzpfbdrxugvdfzqhyefrfirsrvisrpgjjrsvawldmjywhnjupynvmtnzikrzsxkrnzodqwjeobzqpqcavzzzvjixxopwqjhwkcqjuuffobmxfpvjtmkdrowiqwdifmnddfirzfbrbuwjoznrorjqclqjzlsaefidvkxwpvtylalggjvyeecybyohhxkttsieghrniewwiylrxxnhhnhigschbfmwhmaezvbkvkcqquiclmbovisffjkuzfxfphagmljtdprnealogvxptzrojfqfefibkcavzsmcgwkjzksgjuwkrdrpmhwaztlgrtjhkugtxubtteuiqyzubzlcdewetsufzakqkisxkjmsncbkujwqctanhhoynyfrgvrwndarnalceksbvblxcfxlpobyyzgzmnheewvcegkjpxxmdloryifvukekkwaltofowuevznjbjhkgkhlueqkxnkyliiyoutnaemvlcbzsgjwytgxfdxzevdlozhdqflnksubzmlepduejdguacetwvkqbsjlznuudlpkduarcndacrcyyqptgmlcthgqxwahwuqzivhucoithrcibkwceuykaxgkpkdvjkqtlvkhaphufxpuduzxplavcvyyxfzcrhwszqlhploqizwuquzsebodzdcturhcyvceptdkjtrdglgwrkyhclbhwwmuvwceapkunfzhihsdxyjedqeitbbauaexkarrqiozlovvyccvzrmvlqqmdefywldjbpnaysmaukiikmdpiacujlyppdwmdmnjnltfhigmljyyepvyyhxckfdqgdqlievpcmercytvfdslxkjkquluuzpevuugwfzojhwtsiynymklzzvrmpwxdricdifwjxgdzsryxiqgdgqknfvvtpypztblaofvzgunskcgmezhwgncktcpcbjdfolzxwcyvdcheoprleiyrlcsnkxghohnfygsoxxdyaxvivwcbclucffkzgtrqqwsqreuxaeziguwmllzbcecccytcrdsofiaxkudhmqkqgxbzbgyherjtaiwddquuwhztdckfwgegnfbonxgepjlsjontfhnpvmlatauojzeuwsqkyvapjeeqkqhdgldgasbpyvfcojzhkimmmnrpqmgvnlbqkphvqmxtfjffjdeerrfddldghsllolapnuvxjhmqztyeurqkehlxsdcepyfgupewkkuxjzddhqylbtpjemkcihqfnoecvwrfcoftcpkmsnclrgwkirqqlekcoukgbbctniktohnutbftiuyaijjumjecccqmjyohfdhxqfbdahirwdhyvtkmepsqbyvdqzenzuoazvbtfgrqityxwmjkdgslgcvtovvrmxsbujmmimsqzumwrlovalbhhvtzjyyrafawjkeweoukvffgyfwkcbbkkcgizhxkqxnlgwgmksubtxkhcywfiedtrjaczlibrtxofnamkiavcxlaaikqaopaytdleghjxefvaknxyhabuvzjmpmlfldcegffomvtzrlfmhvrrnpoeztorhchutpjchrlrogfuiyguctdqlqolfwinwvxuqwaungcsqhrqrzqznbnegfvjitoqwpayycvgyrtrfsoaddobgihejwdmbzferilnjdvowsyubmtbrajeuzmfymtsozdhomeffjwbbzawgliucrtxurjixcgjlbbxtcljlixoeiaedidjjnebnhctfxdcyncwdjzejdpjekrwagazjiidlntpvpytwnhcmrzygeaxey";
        b = "cggnnwczfciuyocvwecjrdbchuaorxbpsvoxfzmgqahkpbygjyicyaglppzieszlygovjamtueuywnsrpvmcozkyqnwedujtpwbnuhqgfblninhpowleieoolwajmjsthrhaswnahgmfdpltcadvhknevkmlvjddgwirfuehzcckoeryshtyqrjkjeqrjbmkaownluckothmopuwrrdakephemxswsvfesvijtklegjcjrlifdwxdwfyusdcdikpmvtqjoqmpqplfntiombhhzspyrnkxfijacyhqnxqeyqlylpvbvannjdrnnipuviljnjcbwmtrykqejzgdqlxqdtugrzpfqxfupufnfqxbxittzmjgnqxjwzigkojknhlltfniosqbsvquspyodvjbbdzesgyuhdrtmflfnowigjhmswkuuvbithjylkfapkinkuxsuknxbffapuxfmmmfplyeagenyrzkybxqopmljwsidwwyxcmffobaljglajdsegsvabttvjvtyjiowezktprxkalynohnululuksxyozbozqskfngrlpfwahufizivptuqjcqhddozsvvckvpaacusydcoxcqsoqzsuaneoedvblctqrbirlzgjypsvlkwejvawzyfavkzlqtasqjcejhgnqzniiuthdrhlepcvtqykyfncyvlsjnxtudldgdjvrmhwovlswgpbgbbpeppylhzvqgjfoqllyrvrirydaqxjrlmryuyicaibmkyjacqhcxonzqslciojonzhtpflrrpimyazfzlggrsbfkjrxtnhjmsdmpnovlxftiwduefykuhqlwhxcpawhsuqioqsogcaojgmxntpsmckjkpvpszzzisziinzkvlgxlmuovhylsrrlmvmjmlhrbnlffqffaatjuknunajeniutwnotnjxioeqmtipexnkidwqqhakeevlssjfcowtmidpwhwoniruvvxtslpopytjetkjzjlplyzihlsvdsbjerddaazfekmtmwnzmrsrgapectkotsgqftlzkbgpwyvbdnijgmhogzchoybylkmdnlwlvylpwpordrsexdiajqaydkzhjbalyrnnajfwrfsidbkdvqfyqkxzdytotseynehvdndwctbmiokiujrmxcwtxbytxsmucptlivgiubcmhsksofrygyoraxcvkvfmgpjvgijzudkvjgbzklfvsdlkvcljwtcjffuinjewsvpimwtnkldjvxuixixrysmsdenqnjhgbkcsicmjmjdfmtkvyvghrrbixihugffsdciylpzubdfmkmqfatscvwunofdgaggxieclyeawoqhatuhczzyenrnjckuqovfwlinfviolqmmmxhitbcveveejndtmqheqyhdntmyjvkycanwqimzatrgjxtmpqrgivjpakagjvoldtfoumwpolzfttgmujzmnvoatuehwocqqzokvcpvyhgyiwhvgxkeyyvmtzjezvvtusjwxsxtksjfycsgjnnjtuwaacyctttpzolnzhpmuchqfcstempnxrehpmewjjshfemirsunfijxipqxyksoucpirittoezmmvsidqykznezmdopvalhezeoxwqhcfbdtmozqvamkvgwcpodibpdpyfurmeajsnpzbqqdjpdoyzezjqjoouozuwxvpfuoabbraahwdxawtgwqefpprrsbhemrikxobeewxzhzohknyonoekrlflfxhvizliqilcnygwmtmqupctwraeiejwjdxavtqonyeqrtzeiqtsijlbrysdcswtekqtjdrbfhrqswwalhsepkdqvavpncfzglxrxishojsloqigxfxbravffsyruqoxvcgwlczjzodzishvwbocvxjngrafurgiriamhhfaqbppusogpmcmetxilsmnbcyvqcgchcmlzbagfsfckahxxuqzwgbrrgnuzwuejyqlwtikvfnnoirxdsnyguahxwnziyvbluafhmhqtumfnmyffzvphglknoklvkyqtimfdvxptnumlfcvfojoxhuguzcgcywofvfneppqtdjyatlcvunrlqgdavqxyzgmbpbaokqigjubuzuhgdorncznodlyaxvbrcdhqszyuonmgsghrefqfvutkntjrpsxvydxfwrswbftsqqmpyajlnzekuyghbkibappdutxfsygqszijuxrgxpnriybzgkjfdkdkwtfoqafeypheapxahanziwdqrhjynanlvrvbfltopczrluwqpmazyoeroocprvrynhqzihwzockizjiqycupnizgtyihoifdxqdankufadwzcuywfbhhqarttnglthpseakgvnchmcxvgqcxmjstslxggdnrdyhedsvnhwxfnyqfvfhhkrzftfvtbyhweepcavhucksxxyuxorestbswamslktjcsnnrvfrpadhfzwmffjpiheltpckceucmngsejwwfbdsqclludbsthqoxefalwprqhsklicegdcoznksqzghwsxkfydpunalqqfjuxjkslkmexbeoefryllzrztmjgdtcnltdaeiptqmjxzmtsngevpshbxkhcszryucuhheiouojljnpycvpwzpdcloxtjmphksitighznhuxqjgdbyzeprpdwnotzhcmaydmmhakprjwmitkqsmwzizvhsboezendtrruqaepikkdgrjuvkwpogbyqwfodyuqfhftlhlhbvnjfchkqtaloopooduesncvwwygjxiafuinbbwlrliqssvebnworiwfxpwoetgxeflyoabhdpjpyawridtdjqcetzlpqkssuaqtplhtuorjbakssnomxbscqdxlfpfmbeqixmwirmmspzbwfgprrrdddtskumndnpipungesvrovpvyfvyjbdatotzpxeymdwoeiicatmibfbboolpgaykdyjmqkgatzlkeaypjjovncytcpmvkduwmwxwriiucsvwvopcdsdgxmrlsxuplptxopqitqfcsavrofukykctrsqkwojzmtlgbjqqkhagkuvfbjodamuswtivawldnomgucizzbjhxcjneqcxhdsllijswhfitorudmegkkkvxkspbzglmysxfrnhuhljasmftttsrxjhuafqfkcagbokrgmfpuvudtvedjgyciksgdkrikbcmhkrgxaszmhzptbxgslmjkqkzkxswccnomufabcwblkigecqbvjvdwyntbapbehybbuhvciqscxxddynbzkmtuaojimxfrnykeuxrotbgvbbqyajjbfyuvatkikpoaqjmxtuggcdefamrcchwjyxwafcclrwimczdsjaubptvpvxmzqenflwizyrbrnrxtsvrmilewtjriwoytsrhuwznhffjsojtuhsdhondvphwensrsbioidpobuvswfqanavzilwcumxiqgtkyksxwpvyhiyomcgxvkuzsucbnpmycfucexcouivvctlwmgymuuitcfhpblbpjkiihggwkzemwnexhzebkziiuvpsddxjefhridypjkvwxpkccekozcsfzopzbiukdpltfcgsyyuihmnrzxdsvucbfjsnebfxrmabsuzaxyetupydwkhuhrlvycucjbqnudldjkttqqhhsnksquhqiccnzppuwvjgstnnqrqdrolbkfunbfbhtnduoinmwtlyijqsxdbtfephkdhhnjgcjpwdnrriotfduafbrgihougjdxiycsievrmjsxmcusxuawmjrkmvjmsqqdncyqvklwkrhmubtoyfvqiducjtfjzqhalixbrntkluudvehjgzydkqvbtgnzgckrymgjdrgqypguhiyxctvgobmokfycabknbpodeazrpwdphwfyxpskspybjgghqfletdlyxahdeqrsihriuvzncmljuzmopkxoavmqvsvyuvgsuyz";


        a = "pvhmupgqeltozftlmfjjde";
        b = "yjgpzbezspnnpszebzmhvp";


        boolean f = handler.checkPalindromeFormation(a, b);
        System.out.println(f);

    }

    public boolean checkPalindromeFormation(String a, String b) {
        //Situation 1 or  Situation 2
        if (validate(a) || validate(b)) return true;
        int n = a.length();
        int l = 0;
        //Situation 3
        while (a.charAt(l) == b.charAt(n - 1 - l)) l++;
        if (validate(a.substring(l, n - l)) || validate(b.substring(l, n - l))) return true;
        l = 0;
        //Situation 4
        while (b.charAt(l) == a.charAt(n - 1 - l)) l++;
        if (validate(b.substring(l, n - l)) || validate(a.substring(l, n - l))) return true;
        return false;
    }


    /**
     * TLE 50%的用例
     *
     * @param a
     * @param b
     * @return
     */
    public boolean checkPalindromeFormation1st(String a, String b) {
        long start = System.currentTimeMillis();
        int n = a.length();
        for (int i = 0; i < n; i++) {
            String aPrefix = a.substring(0, i);
            String aSuffix = a.substring(i);
            String bPrefix = b.substring(0, i);
            String bSuffix = b.substring(i);
            System.out.printf("aPrefix:%s,aSuffix:%s,bPrefix:%s,bSuffix:%s\n", aPrefix, aSuffix, bPrefix, bSuffix);
            if (validate(aPrefix + bSuffix) || validate(bPrefix + aSuffix)) {
                return true;
            }
        }
        System.out.println(System.currentTimeMillis() - start);
        return false;
    }


    private boolean validate(String s) {
        int l = 0, r = s.length() - 1;
        while (l < r) {
            if (s.charAt(l++) != s.charAt(r--)) return false;
        }
        return true;
    }


}
